### ISSUE TITLE
Small fixes to UI

### ISSUE THREAD

**Issue by KiviluomaNeera** [koodikilpparit/sanapolku#154]
Pari ongelmaa asetukset sivulla korjattu jo, mihin ensimmäinen kommentti viittaa. Nämä on poistettu listalta.
 
Korjattavia asioita: 
- Korjaa tekijät olemaan omilla riveillään asetukset sivulla
- Asetukset nappi menee logon kanssa päällekkäin etusivulla (sama ongelma myös latausnapin kanssa, jos se ehtii mainiin näihin korjauksiin mennessä)
- Asetukset sivun Tietoa sovelluksesta osion eri osioiden otsikkojen fonttikokoa voisi pienentää
- Tietoa sovelluksesta osio leveämmäksi mobiililla
- Korjaa jaksotus ja lopetusnäkymien kuvat olemaan isompia isommilla näytöillä

**Comment by Majis-R** [comment]
Pyrin korjaamaan kaksi ekaa ongelmaa [tässä](https://github.com/koodikilpparit/sanapolku/pull/228/commits/f4f86283255d483789ceebbd7f429937a82a89f5) commitissa. Commit on osana Issueta #188
