### ISSUE TITLE
Fix modals on narrow screen

### ISSUE THREAD

**Issue by pampula** [koodikilpparit/sanapolku#236]
Kun ruutua kaventaa, modaali hyppää sivun ylös, jolloin sen yläosa menee piiloon. Korjaa modaalia niin, että se pysyy keskellä sivua jokaisella ruudun koolla.

**Comment by KiviluomaNeera** [comment]
Tätä on jo korjattu issuen #200 yhteydessä jakamisen modaaleihin. Sieltä voi ottaa mallia
