### ISSUE TITLE
Fix papunet photo fetch

### ISSUE THREAD

**Issue by KiviluomaNeera** [koodikilpparit/sanapolku#267]
Nyt papunetin kuvahaku hakee uudet kuvat aina, kun hakukenttään kirjoitettua sanaa muokataan. Korjaa kuvien haku tapahtumaan vain, kun painetaan Hae kuvia -nappia.

**Comment by juhor00** [comment]
Uusi useEffect aiheuttaa 3 hakua yhden sijaan aina kun komponentti (PapunetPhotoView) renderöidään. Sen lisäksi tuo muuttuva search term aiheuttaa lisää hakuja aina.
Tarkoitus olisi siis vain kerran hakea aluksi, ja sen jälkeen automaattiset haut tapahtuvat kun filttereitä muokataan. Muutoin vain napin painalluksesta tehdään uusi haku.
