### ISSUE TITLE
Papunet images are stretched

### ISSUE THREAD

**Issue by juhor00** [koodikilpparit/sanapolku#268]
Papunet kuvat ovat listanäkymässä venytettyinä, eikä alkuperäisessä kuvasuhteessa. Pidä laatat samankokoisina kuin nyt, mutta pakota kuvalle alkuperäinen kuvasuhde. Todennäköiseisesti kuvat siis pienenevät ainakin johonkin suuntaan, mutta se on ok.

Pelissä tietyillä näytönkooilla kuva venyy (korjataanko?)

**Comment by KiviluomaNeera** [comment]
Korjaantuu toisen issuen yhteydessä
