### ISSUE TITLE
Enhance the UI

### ISSUE THREAD

**Issue by KiviluomaNeera** [koodikilpparit/sanapolku#28]
Alle voi listata kehityksen aikana huomattuja ongelmia käyttöliittymän kanssa:

- Kännykällä vaakatasossa kuusitausta näkyviin, jos ei ole polkuja
- Hitusen pidemmällä polun nimellä kännykällä editointi, poisto ja jakonapit liukuvat ulos ruudusta, jolloin niitä ei voi enää käyttää (Kuva kommenteissa). Mallia voi varmaankin ottaa pitkän sanan käsittelystä polun muokkauksen sivulta
- Polun jakamisen vastaanottamisen ponnahdusikkunassa Palaa Takaisin nappia voisi pienentää (ei näy ainakaan Juhon tabletilla kokonaan :D)

Listatut ongelmat korjataan tämän tiketin yhteydessä.

**Comment by juhor00** [comment]
![Image](https://github.com/user-attachments/assets/34be508e-f13f-48ef-a482-bbc1c570cca0)
