### ISSUE TITLE
PWA does not work on mobile

### ISSUE THREAD

**Issue by KiviluomaNeera** [koodikilpparit/sanapolku#61]
Puhelimella sovellus ei ehdota PWA:ta ladattavaksi. Selvittele miksi ja make it work, yay! Tsekkaile samalla, että kaikki toimii PWA sovelluksenkin puolella kuten pitäisi.

**Comment by juhor00** [comment]
Tarkempaa infoa löytyy Chrome DevTooleista Application -> Manifest
![Image](https://github.com/user-attachments/assets/e5310c97-d92b-41a3-a252-f0e32269c601)

**Comment by annikniem** [comment]
Lisäsin tähän itseni, kun korjasin nuo logo/ikoni ongelmat niin samalla perhedyin myös muihin ongelmiin mistä tuo herjasi. Teen erillisen issuen tuosta preview screenshottien lisäämisestä, mistä tuo myös herjaa ja käyn tekemässä sen.
