### ISSUE TITLE
Study best way to implement path sharing between devices

### ISSUE THREAD

**Issue by KiviluomaNeera** [koodikilpparit/sanapolku#66]
Selvittele millä tekniikalla lähdetään toteuttamaan polkujen jakaminen laitteiden välillä.
Vaihtoehtoja:
- WebRTC (https://github.com/AquiGorka/webrtc-qr)
- Bluetooth
- Wifi-Direct

**Comment by juhor00** [comment]
https://libp2p.io/
https://webrtc.org/
https://ipfs.tech/

Lisään issuen yhteyteen näitä mitä kirjattu muualle ylös.

**Comment by juhor00** [comment]
Nyt on tutkittu vähän sitä sun tätä

## TL;DR
WebRTC jollain ilmaisella signaling-palvelimella:
-  https://peerjs.com/peerserver
- https://github.com/mafintosh/signalhub?tab=readme-ov-file

Jos ei toimi niin ollaan kusessa ja pitää joku aivan hirveä purkkaratkaisu tehdä :D

## Web Bluetooth API
Ei sovellu, vaatii että toinen laitteista on ns peripheral (ei mahdollista web app)

## WiFi Direct
Muistaakseni ei ole varteenotettava vaihtoehto koska web applikaatiolla ei ole pääsyä suoraan tähän rajapintaan. Olisi hyvin hyvin manuaalinen homma jonka käyttäjien pitäisi tehdä, eikä välttämättä silti toimisi.

## WebRTC
Peer-to-peer kommunikaatio protokolla. Eli itse tiedostojen lähettäminen ei vaadi palvelinta väliin ja on turvallinen.
Vaatii kuitenkin jonkin keinon millä osapuolet löytävät toisensa. Normaalisti käytetään signaling-palvelinta tähän. Koska olemme köyhiä, niin vaihtoehdot ovat:

1. QR koodeilla välittää protokollan handshake data. Ei ole kuitenkaan aukotonta, sillä vaadittava viestin määrä ei ole vakio vaan riippuu monista tekijöistä kuten verkkoasetuksista ja palomuureista. Laitteet todennäköisesti ovat eri verkoissa (esim. toinen WiFi ja toinen mobiiliverkossa). **Ei** ole kannattava.
2. Käytetään jotain ilmaiseksi tarjolla olevaa signaling-palvelinta. Itse tiedonsiirto on kuitenkin kahden käyttäjän välillä, eikä itse data kulje koskaan tuon palvelimen kautta.

Näistä kahdesta WebRTC menetelmästä siis vain tuo signaling-palvelin on ainoa järkevä vaihtoehto. Löytyi muutamia projekteja jotka tarjoavat näitä ilmaisia signaling-palvelimia:

-  https://peerjs.com/peerserver
- https://github.com/mafintosh/signalhub?tab=readme-ov-file

Tuo GitHub projekti näytti hyvin simppeliltä, lähtisin sillä ensin testaamaan.

### Riskit
On mahdollista, että joku samaa signaling palvelinta käyttäen esittää toista osapuolta ja data lähetetään väärälle laitteelle. Saapahan sitten kissakuvat. Pitää painottaa asiakkaalle että mitään sensitiivistä dataa ei tule lähettää käyttäen tätä sovellusta. On myös mahdollista, että joku lähettää "väärää" dataa jos esittää lähettäjää. En näe mitään kriittistä näissä kuitenkaan.

## Random file share palvelut mitä voi ilmaiseksi käyttää
Ei vakuuttanut, mainoksia siellä täällä, ei saa helposti integroitua käyttäjän selaimesta. Jotkut palvelut toimivat huonosti. Osa vaikutti epäluotettavalta. UX samaa tasoa kuin seuraavassa ehdotuksessa (huono).

## Muita tapoja
Näitä en ole tarkemmin tutkinut koska ajatus näistä on aika kehnoja

- Käyttäjä lataa polun (joku .zip esim), lähettää suoraan omasta sähköpostistaan toisen sähköpostiin tiedostot. Toinen sitten uploadaa sivulle sen tiedoston ja uusi polku ilmestyy. Niiden lataaminen on manuaalista ja vaatii käyttäjiltä sähköpostien lähettelyä. Toisaalta hyvin varma tapa saada data turvallisesti perille.
- Pelkillä QR koodeilla saisi tekstin lähetettyä, mutta kuvia ei mitenkään saa mahtumaan. (Vajaa 3kb max ja sekin on järkyttävän iso QR koodi)
- Otetaan itse joku ilmainen plan jostain hosting palvelusta ja väsätään tällainen väliaikainen share palvelu
  - Aivan liian iso tässä vaiheessa ottaa tämän projektin skooppiin nähden
