### ISSUE TITLE
Fetching photos from papunet

### ISSUE THREAD

**Issue by KiviluomaNeera** [koodikilpparit/sanapolku#67]
Selvittele miten Papunetin APIsta saisi haettua kuvia sovelluksen käyttöön. Toteuta toiminnallisuus kuvien hakemiselle hakusanan avulla. Kuvia pitää pystyä hakemaan Papunetistä löytyvien eri kuvatyyppien mukaan käyttäjän antamien rajauksien perusteella.

Tsekkaa kuvien koon skaalautuvuutta. Uuden sanan lisäyksen yhteydestä voi ottaa mallia.

Tämän issuen aikana kuvien hakua ei vielä liitetä osaksi oman polun luomista vaan se toteutetaan myöhemmässä issuessa. Eli pelkkä toiminnallisuus riittää, eikä käyttöliittymäelementtejä yms. tarvitse vielä murehtia.

**Comment by KiviluomaNeera** [comment]
Tässä APIn dokumentaatio:

![Image](https://github.com/user-attachments/assets/72839871-7acc-479f-afdc-e3381bae53a1)

**Comment by Majis-R** [comment]
Tein kuvien liittämisen osaksi omaa polkua koska oli suht helppo. Filtteröintiä en tee apia käyttäen vaan haen kaikki kuvatyypit ja sitten filtteröidään UI:ssa. Näin vähemmän api kutsuja. Teen myös alustavan käyttöliittymän jotta päästään näkemään että api oikeasti palauttaa kuvia joita voidaan näyttää
