### ISSUE TITLE
Online-first caching mechanism does not work

### ISSUE THREAD

**Issue by juhor00** [koodikilpparit/sanapolku#72]
Uusin versio pushattu ja buildattu jo Pages-sivulle, mutta selain antaa vanhan version siitä. Online-first menetelmä ei toimi oikein, eli että uusin versio haettaisiin palvelimelta ensisijaisesti.

**Comment by KiviluomaNeera** [comment]
Ei ehditä toteuttaa eikä ollut asiakkaan vaatimuus. Jätetään tekemättä.
