### ISSUE TITLE
Plan and prepare for usability testing

### ISSUE THREAD

**Issue by KiviluomaNeera** [koodikilpparit/sanapolku#74]
Käyttäjätestauksen suunnittelua ja siihen valmistautumista.

Tähän löytyy OneDrive kansiosta nyt tiedosto "Käyttäjätestaussuunnitelma".

**Comment by tuulijar** [comment]
Kävin kirjottaa tohon suunnitelma-tiedostoon kysymyksiä ja ideoita/ajatuksia ihan vaan tolleen muistiinpanoina, nii on vähä runkoa mistä jatkaa.
