### ISSUE TITLE
Reset Database

### ISSUE THREAD

**Issue by Majis-R** [koodikilpparit/sanapolku#78]
There needs to be a function that resets the database. The current version of the function was written as a part of issue #5. Currently it completely empties the database except for images and those are left without anything to reference them. 

https://github.com/koodikilpparit/sanapolku/blob/1800be0411808275b8b103a6fb41e46ee0d87c87/src/db/db.js#L162-L195

**Comment by KiviluomaNeera** [comment]
Issue voidaankin poistaa, sillä tämä toiminnallisuus toteutuukin jo.
